### ISSUE TITLE
Проблема двух спрайтов.

### ISSUE THREAD

**Issue by iamblood** [animusdev/white#120]
Два спрайта не имеют спрайта вообще. Спрайты, которые я заметил: Шляпа повара(не имеет спрайта, когда находится в руке и выглядит, будто это одежда повара.)
Одежда в церкви. Когда её снимаешь на половину - пропадает спрайт и выглядит он так, будто бы на тебе нет одежды.
![684658cde548a41ceaf16883afbf09e1](https://cloud.githubusercontent.com/assets/25691138/22835917/79765490-efcb-11e6-84df-102775806fb3.png)

**Comment by rainbowjose** [comment]
Тгшники чинят
