### ISSUE TITLE
Серьезный баг, с помощью которого можно удалять предметы.

### ISSUE THREAD

**Issue by iamblood** [animusdev/white#121]
Суть бага заключается в том, что когда ты снимаешь сумку, зажимая на нем левой кнопкой мышкой и переносишь на предмет, который у тебя в руке - случается такая вот вещь.
Сумка просто пропадает. Её нет больше в игре и ты никак не можешь её вернуть.
Таким образом, я удалял диск ядерной аутификации и вообще - любые предметы, которые можно положить в сумку.
Проверял по такой схеме: Рюкзак на сумку, в левой руке джетпак из ЕВА и делаю то, что описал выше. (возможно работает с любым предметом, но я проверял именно с этим.)

**Comment by rainbowjose** [comment]
https://github.com/tgstation/tgstation/issues/23794
