### ISSUE TITLE
Как заставить сервер лагать с помощью Welding Helmet

### ISSUE THREAD

**Issue by iamblood** [animusdev/white#122]
Если быстро кликать на welding helmet, другими словами, снимать и одевать его через кнопку на худе, то сервер начинает очень сильно лагать и зависать.

![b85d73dde84b7e53b8002c186f23aeba](https://cloud.githubusercontent.com/assets/25691138/22835138/c9bb74ba-efc8-11e6-8b76-40d456a6773a.png)

**Comment by Osokorn** [comment]
Решено. Заходим на ТГ, все вместе начинаем кликать велдинг хелмет, они фиксят, мы мержимся.

**Comment by rainbowjose** [comment]
Отличный план.

**Comment by rainbowjose** [comment]
Адресовал тгшникам.
