### ISSUE TITLE
Невидимая нога.

### ISSUE THREAD

**Issue by iamblood** [animusdev/white#123]
Когда тебе пришивают руку из нового ящика в медбее - она становится невидимая, но по статам она есть.
Скриншот не получилось сделать, кидаю логи.

Allen Clewett asks, "Вы пришили?"
Elias Blessig says, "Полежи еще."
Elias Blessig has grabbed Saburo Chukwumereije passively!
Allen Clewett says, "Если да, то нога невидимая."
Elias Blessig has grabbed Saburo Chukwumereije aggressively!
Elias Blessig asks, "Да?"
Elias Blessig asks, "Почему?"
Saburo Chukwumereije asks, "Вы дебилы?"
Allen Clewett says, "Да."
Saburo Chukwumereije says, "А."
Saburo Chukwumereije says, "Все норм."
Saburo Chukwumereije says, "Спасибо."
Allen Clewett squashed the cockroach.
Elias Blessig says, "СМО говорит, что нога невидимая."

**Comment by rainbowjose** [comment]
Спасибо. Это тгшный баг, так что в общем-то их ждем.
