### ISSUE TITLE
Сломанная буква "я" (до сих пор не пофиксили, шок)

### ISSUE THREAD

**Issue by iamblood** [animusdev/white#124]
Сломанная буква я. 
![a819f7b699c3cfde31b028daecf7f819](https://cloud.githubusercontent.com/assets/25691138/22842229/9981bb8e-efe5-11e6-9bbb-53f4f72e7def.png)

**Comment by rainbowjose** [comment]
Это у сервантов и а аннонсментов, прямо сейчас чиню.

**Comment by rainbowjose** [comment]
Поправил.
