### ISSUE TITLE
"Я" сломана в речи культистов

### ISSUE THREAD

**Issue by ModernViolence** [animusdev/white#139]
https://www.screencast.com/t/7kd4slgLz4

Уверен, что у ратварианцев та же фигня.

Отуска - мы с тобой. Ты сможешь.

**Comment by rainbowjose** [comment]
Ну пофиксили же!

**Comment by ModernViolence** [comment]
На момент заведения бага - воспроизводилось на вайте.

**Comment by rainbowjose** [comment]
Если увидите еще - трубите

**Comment by ModernViolence** [comment]
У ратварианцев таки сломано.

https://www.screencast.com/t/Qi3rt1hyw
