### ISSUE TITLE
линет ебло

### ISSUE THREAD

**Issue by Euronem** [animusdev/white#20]
где мои шмотки в виде берета охраны?

**Comment by Ein-Linet** [comment]
>animusdev member

Але, деб, возьми и запили.

**Comment by Euronem** [comment]
Я не хочу форкать и делать ПР

**Comment by Ein-Linet** [comment]
А с доступом ты, типа, запилишь?

**Comment by Ein-Linet** [comment]
Получил доступ к репе и пошел пилить билд своей мечты.
