### ISSUE TITLE
Мутаген не дает симптомов

### ISSUE THREAD

**Issue by Qwertyon666** [animusdev/white#79]
Взял кровь, налил в баночку, капнул мутагена, симптомов нет.
Налил по колбы мутагена, симптомов опять нет.
Хуярил этим мутагеном по всем пробиркам с кровью, а симптомов Н Е Т.

**Comment by Shluher** [comment]
в крови хоть базовая вирусня была?

**Comment by Shluher** [comment]
а так на теге сейчас специальная хуйня есть для мутаций

**Comment by Shluher** [comment]
её сварганить попробуй там.

**Comment by Qwertyon666** [comment]
В общем, дело в том, что с чистой кровью это не работает, он заставляет мутировать сам вирус
Поэтому нужно капнуть вирус в кровь и уже потом подливать мутагена
